version: '3.1'

services:

  rabbit:
    image: 'rabbitmq:3-management'
    environment:
      RABBITMQ_ERLANG-COOKIE: 'SWQ0K0DSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - "15672:15672" # Available to Web
      - "5672:5672" # To connect systems
